### ISSUE TITLE
Use of undeclared identifier 'pushRegistry' in AppDelegate.m

### ISSUE THREAD

**Issue by gorohovgame** [react-native-webrtc/react-native-voip-push-notification#12]
Hello please help,
all install, link lib., add PushLit.framework  ( iOS 10.2)

and  - Use of undeclared identifier 'pushRegistry' in AppDelegate.m
dont und. what to do :(

![default](https://user-images.githubusercontent.com/11030363/32100649-423fef54-bb1d-11e7-98fe-83a99f57f7c1.PNG)
![2](https://user-images.githubusercontent.com/11030363/32100689-6673e268-bb1d-11e7-95dd-eba7a6d2a1b6.PNG)

**Comment by niocncn** [comment]
Try to add headers path.

**Comment by jdegger** [comment]
For anyone encountering the issue above. The Pushkit method should be added BELOW existing method, not as part of the method.

**Comment by jo74705** [comment]
@jdegger Sorry, I can't understand what you said.
Can you post a screenshot?

**Comment by dheerendra9414** [comment]
Do not add the code inside the didFinishLaunchingWithOptions but add it rather outside and i'll work
