### ISSUE TITLE
Notification not received after app killed

### ISSUE THREAD

**Issue by timmeh-m** [react-native-webrtc/react-native-voip-push-notification#14]
I have implemented this library with the RNCallKit library and nearly every time a notification is sent to the device, the notification is received and Call Kit does it's magic. However, there have been instances where after the app launches I kill the app, lock the device and let it go to sleep, then send a notification again. The notification is not received. If I simply wake the device (not unlock it, just let the screen light up), then the notification comes through and CallKit works. As far as I can tell, the didReceiveIncomingPushWithPayload in AppDelegate.m is not called. The notification is of type VoIP. Has anyone figured this out?

**Comment by aarkalyk** [comment]
@timmeh-m I've been having the issue with a killed app as well. Then I tried to build the app in release mode instead of debug and everything worked like magic :)

**Comment by pmagnussen** [comment]
I believe that there is some logic in iOS that disables push notifications in case the user kills the app. However, if the iOS system kills the app (to conserve memory, etc) then the app should handle the push notification.

**Comment by platonish** [comment]
@timmeh-m @pmagnussen Is there a solution to this?

**Comment by pmagnussen** [comment]
@platonish Not that I know of. The last time I checked, this is an intentional security mechanism put in place by Apple. Long story short, there is no way around it.

**Comment by danghung24031992** [comment]
I try to write in Appdelegate is work
- (void)registerUserNotification:(UIApplication *)app
{
  UIUserNotificationType types = UIUserNotificationTypeNone;
  types = UIUserNotificationTypeAlert | UIUserNotificationTypeBadge | UIUserNotificationTypeSound;
  
  UIUserNotificationSettings *notificationSettings =
  [UIUserNotificationSettings settingsForTypes:(NSUInteger)types categories:nil];
  [app registerUserNotificationSettings:notificationSettings];
}

- (void)voipRegistration
{
  //  NSLog(@"[RNVoipPushNotificationManager] voipRegistration");
  __weak AppDelegate *weakSelf = self;
  dispatch_queue_t mainQueue = dispatch_get_main_queue();
  dispatch_async(mainQueue, ^{
    // Create a push registry object
    weakSelf.voipRegistry = [[PKPushRegistry alloc] initWithQueue: mainQueue];
    // Set the registry's delegate to AppDelegate
    weakSelf.voipRegistry.delegate = weakSelf;
    // Set the push type to VoIP
    weakSelf.voipRegistry.desiredPushTypes = [NSSet setWithObject:PKPushTypeVoIP];
  });
}
