### ISSUE TITLE
Support for iOS 11+

### ISSUE THREAD

**Issue by eashevchenko** [react-native-webrtc/react-native-voip-push-notification#15]
I ve used this module for voip PN. All is good with iOS 9 and iOS 10, but on iOS 11 I can't receive voip PN also can't see voip token. How I can resolve this ?

**Comment by ianlin** [comment]
Well I have no problems with iOS 11, can you share more information about e.g. device, code snippet etc?

**Comment by eashevchenko** [comment]
I tested on iPhone 6s, iPhone 7 yesterday. So when I ve added   wakeupByPush flag (according to example from Readme), I ve  seen voip token, but when to close application (force quit) - nothing was happened. One important question - how to wake up application using Voip on iOS 11.1 ? If I m not mistaken - Apple removed Voip socket on this iOS version...

**Comment by ianlin** [comment]
Probably related to [this][1]. You can try adding `voip` in your `Info.plist` manually.

[1]: https://stackoverflow.com/questions/45025731/voipvoice-over-ip-missing-in-xcode-9

**Comment by ianlin** [comment]
Yeah we also use CallKit in our project. I'm not sure this is the reason leads to PushKit not working but CallKit is worth to use as it has better UX for the user.

**Comment by eashevchenko** [comment]
When I added RNCallKIt - application on iOS 11 wake up from terminate state to background when Voip PN was received. But when I close application (force quit) again - nothing happened. I can' t register push token again. Maybe this related with [this](https://github.com/ianlin/react-native-voip-push-notification/issues/14) issue ?
