### ISSUE TITLE
Is there a way to "unregister"?

### ISSUE THREAD

**Issue by rcorrie** [react-native-webrtc/react-native-voip-push-notification#17]
How does one go about unregistering the device (for example, on Log Out).

**Comment by anhtukhtn** [comment]
I'm looking for that, too.

**Comment by zxcpoiu** [comment]
AFAIK, it's not possible :(

**Comment by wilmxre** [comment]
@rcorrie @anhtukhtn @zxcpoiu hey guys, did you manage to unregister on logout?

**Comment by Romick2005** [comment]
Just remove device voip token from you server as available to receive voip push token. I am using OneSignal on server side to send voip or high priority notifications for the call. So I have full control on the server side. Just need to do cleanup voip token on logout.

**Comment by wilmxre** [comment]
i don't have access to the server side. my scenario is like this: i get a background notification from firebase when i have to log out from my app. when my app is in background or killed state after i get the logout notification from firebase i remove my tokens, clear storage, unregister from events, but i still get the voip notification. i call this function: ```VoipPushNotification.removeEventListener('notification')```. shouldn't this unregister from the voip notification event?

**Comment by Romick2005** [comment]
Nope as server is still sending voip notification to the device and it should be shown when device receives it
