### ISSUE TITLE
'React/RCTBridgeModule.h' file not found when building project

### ISSUE THREAD

**Issue by BorregoIgnacio2** [react-native-webrtc/react-native-voip-push-notification#18]
Followed the install instructions per the documentation, and Xcode yields the following error when building: 

'React/RCTBridgeModule.h' file not found 

from the file 'RNVoipPushNotificationManager.m'. 

Any guidance as to why this might be happening would be greatly appreciated!

**Comment by jaswantjatav** [comment]
Same errors throw on my screen, anyone can help. ?

**Comment by jaswantjatav** [comment]
I have setup application as per given into document but it is showing the error.

![Screenshot 2019-07-15 at 12 30 15 PM](https://user-images.githubusercontent.com/15123201/61199653-53d5ca00-a6fc-11e9-91c6-c986bc1190de.png)


Please help me to find out the issue, I can't figure it out.

**Comment by kumarutsav111** [comment]
*In your Xcode project, select Build Phases --> Link Binary With Libraries
Add PushKit.framework
*Drag node_modules/react-native-voip-push-notification/ios/RNVoipPushNotification.xcodeproj under <your_xcode_project>/Libraries
*Select <your_xcode_project> --> Build Phases --> Link Binary With Libraries
Drag Libraries/RNVoipPushNotification.xcodeproj/Products/libRNVoipPushNotification.a to Link Binary With Libraries
*Select <your_xcode_project> --> Build Settings
In Header Search Paths, add $(SRCROOT)/../node_modules/react-native-voip-push-notification/ios/RNVoipPushNotification with recursive

**Comment by annie-elequin** [comment]
I just followed the README (manual setup because rnpm is deprecated), and I followed the above steps, but I'm still getting this error. 

What other information would be useful for debugging? 

I'm on Catalina 10.15.1, XCode 11.3, React Native 0.61.4, and react-native-voip-push-notification 1.1.5

**Comment by annie-elequin** [comment]
Update, for people who come here: I had to run `npx react-native unlink react-native-voip-push-notification` in order for it to work. So if you're running over 0.60 for react native, it WILL link it automatically, and you should not follow manual linking options.
