### ISSUE TITLE
Module RNVoipPushnotificationManager requires main queue setup since it overrides ........

### ISSUE THREAD

**Issue by chuchden** [react-native-webrtc/react-native-voip-push-notification#24]
Hello, I got this warning message . 
I can get voip token well, but seem can't get push notification back.
I am new to it. who able to help me on that? I have some budget for that work.

Thanks.

![45807318_484074635333850_8873631419717386240_n](https://user-images.githubusercontent.com/3120637/48302629-75f5c780-e531-11e8-890a-81d49f34fdd0.jpg)

**Comment by Praxey** [comment]
Same thing is happening to me. Not sure what to do...

**Comment by chellongCoder** [comment]
same to me :(

**Comment by StevenGolemme** [comment]
Created #27 to address issue @Praxey @chellongCoder @chuchden

**Comment by zxcpoiu** [comment]
fixed
