### ISSUE TITLE
is it possible to trigger a function when notification received even app closed?

### ISSUE THREAD

**Issue by srhtylmz19** [react-native-webrtc/react-native-voip-push-notification#26]

**Comment by shubham1164** [comment]
I have the same question. Have you found the answer?

**Comment by srhtylmz19** [comment]
i solved the problem by using 'apn' i mean i made my app looks like a voip app

**Comment by shubham1164** [comment]
I have heard that, Apple rejects app with that appraoch

**Comment by zxcpoiu** [comment]
Apple now forced to use voip push with callkit.
You should use something like `remote notification` `background fetch` instead.
