### ISSUE TITLE
Notification event listener is not logging any response

### ISSUE THREAD

**Issue by krajay015** [react-native-webrtc/react-native-voip-push-notification#30]
I'm working with iOS for VoIP notification and I've used react-native-callkit and react-native-voip-push-notification to handle my VoIP calls. 

I'm able to trigger localNotification using the following code:
 ```
VoipPushNotification.presentLocalNotification({alertBody: "Local Notification Test"})
```
but my localNotification listener is not logging out any notifications (my app is on):
```
VoipPushNotification.addEventListener('localNotification', notification => {
      console.log('localnotification notify : ', notification)
    });
```

I've enabled push notification, Background mode (VoIP notification, Background fetch, and Remote notification) from x-code capabilities. I'm using RN0.58. Is something I'm missing?

Thanks in advance

**Comment by platonish** [comment]
@krajay015 Try checking "Remote notifications" and "Background fetch" under Background Modes.

**Comment by krajay015** [comment]
@platonish already done that. Still not getting log in eventListener

**Comment by minh265tv** [comment]
same issue, did anyone resolve that?

**Comment by zxcpoiu** [comment]
Local notification event should be triggered when user click to presented notification.
If you want to receive remote voip push notification, should use event 'notification', and before that, should ask permission and register a valid voip token

**Comment by nikesh8** [comment]
I am also having same problem and I have enabled all the options but still "localNotification" listener doesn't logging anything. Please suggest some way I am stuck at this point.

**Comment by Irfanwani** [comment]
Any update on this. Listeners are not triggered.
