### ISSUE TITLE
Doesn't wake up on background

### ISSUE THREAD

**Issue by zek** [react-native-webrtc/react-native-voip-push-notification#33]
First of all thank you for package :)

My app can receive push notifications when phone screen is on. (app is closed also)

But if I turn off the screen wait like 10-15 seconds I can't get the PN. Is that an expected behavior? I guess not because I can get calls from whatsapp even (whatsapp is closed + screen is off)

Any ideas how to solve this?  

I am running my app on testflight.

**Comment by zek** [comment]
It works as expected. There was problem with my configuration. Sorry for issue.

**Comment by ajnozari** [comment]
Can you let me know what was wrong on your config?  I’m also running into this issue.
