### ISSUE TITLE
Listener 'register' never trigger to get device token

### ISSUE THREAD

**Issue by hinodi** [react-native-webrtc/react-native-voip-push-notification#35]
I was config successfully, but this listener never trigger.
Here is my code:
VoipPushNotification.addEventListener('register', token => {

});

**Comment by JB-CHAUVIN** [comment]
Same issue goes for me.

**Comment by dnolbon** [comment]
it started working when i turned on Push Notifications in Capbilities
Here is my settings which works:
![Screenshot 2019-06-13 at 08 39 17](https://user-images.githubusercontent.com/17106728/59406454-f675f280-8db6-11e9-8c6f-f23bbf1a0624.png)
![Screenshot 2019-06-13 at 08 40 33](https://user-images.githubusercontent.com/17106728/59406455-f675f280-8db6-11e9-9986-34b59bb23562.png)

I hope this helps

**Comment by priyasamyal** [comment]
> it started working when i turned on Push Notifications in Capbilities
> Here is my settings which works:
> ![Screenshot 2019-06-13 at 08 39 17](https://user-images.githubusercontent.com/17106728/59406454-f675f280-8db6-11e9-8c6f-f23bbf1a0624.png)
> ![Screenshot 2019-06-13 at 08 40 33](https://user-images.githubusercontent.com/17106728/59406455-f675f280-8db6-11e9-9986-34b59bb23562.png)
> 
> I hope this helps

Works well Thanks

**Comment by jayrenteria** [comment]
Even with this capability on, I don't reliably register a voip token. Is there a way to retrieve the token if it's already been registered? Or does it fire the register call every time?

**Comment by zxcpoiu** [comment]
Under development ( build via xcode and test  ), no matter Debug or Release, for some unknowing reasons, especially when you install/uninstall switching between `Release/Debug`, will happen.

Even we can see we've call `register` successfully, the ios just stop call `didUpdatePushCredentials` so you never get refreshed token...

There are bunch of questions on the internet, the solution in short:

* clean all data / cache you can, including xcode's Derived Data
* disable / re-enable push related capabilities and background mode
* disable / re-enable signin related auto manage

Then rebuild.

The most upvoted option is: `reboot your device and mac.` 
Sometimes everything did not work, but only after few hours,  it worked suddenly.

Maybe apple's push token server somehow banned the developing app (?)

Anyway, if all steps didn't work. You just uninstall app, clean all data and restart all devices and mac ( close xcode ), then just do another thing. Then try it maybe 2~3 hours later. :(

**Comment by zxcpoiu** [comment]
AFAIK, from my limited experience, there is no way to retrieve / refresh / revoke tokens.
The only thing you know is the token previous stored on your server.

Please share if somebody knows some tricks, even evil's one. :)

**Comment by djalmajr** [comment]
I did all this things and yet, no device token... Can anyone help me with this? Simple demo:

https://github.com/djalmajr/CallKeepDemo

**Comment by jpudysz** [comment]
@djalmajr hard reset your device. It should work

**Comment by oojikoo** [comment]
> Under development ( build via xcode and test ), no matter Debug or Release, for some unknowing reasons, especially when you install/uninstall switching between `Release/Debug`, will happen.
> 
> Even we can see we've call `register` successfully, the ios just stop call `didUpdatePushCredentials` so you never get refreshed token...
> 
> There are bunch of questions on the internet, the solution in short:
> 
> * clean all data / cache you can, including xcode's Derived Data
> * disable / re-enable push related capabilities and background mode
> * disable / re-enable signin related auto manage
> 
> Then rebuild.
> 
> The most upvoted option is: `reboot your device and mac.`
> Sometimes everything did not work, but only after few hours, it worked suddenly.
> 
> Maybe apple's push token server somehow banned the developing app (?)
> 
> Anyway, if all steps didn't work. You just uninstall app, clean all data and restart all devices and mac ( close xcode ), then just do another thing. Then try it maybe 2~3 hours later. :(

"Sometimes everything did not work, but only after few hours, it worked suddenly."
happend to me as well.

**Comment by rajngarg** [comment]
I am having the same issue nothing worked. Please help if anyone made it work.
Thanks in advance

**Comment by stephanoparaskeva** [comment]
What do I do, my 'register' never gets invoked, how do I solve this?

**Comment by stephanoparaskeva** [comment]
j

> Even with this capability on, I don't reliably register a voip token. Is there a way to retrieve the token if it's already been registered? Or does it fire the register call every time?

Did you manage to find a way to reliably register a voip token? mine stopped calling 'register' randomly

**Comment by CMLCNL** [comment]
Same issue, Never triggered i try to everythings..

**Comment by uday8373** [comment]
In my case event is getting called but, the token is coming as empty string always. Please help./
