### ISSUE TITLE
should make registerUserNotification optional

### ISSUE THREAD

**Issue by r0b0t3d** [react-native-webrtc/react-native-voip-push-notification#39]
Hi, I think it would be great if you can make `registerUserNotification` as optional.
1. Voip registration is not required to request notification permission.
2. I am working on a project using `react-native-firebase`. That's mean I already registered for user notification. So I do not want to override my settings when setting up voip push.
3. For ios 10 and above, `[app registerUserNotificationSettings:notificationSettings]` is deprecated. Use UserNotifications Framework's `[UNUserNotificationCenter requestAuthorizationWithOptions:completionHandler:]` and `[UNUserNotificationCenter setNotificationCategories:]` instead

**Comment by zxcpoiu** [comment]
fixed
