### ISSUE TITLE
Cannot install pod after installing this dependency in React Native version>=0.60.0

### ISSUE THREAD

**Issue by vinod20191992** [react-native-webrtc/react-native-voip-push-notification#41]
Below is the error:-

[!] CocoaPods could not find compatible versions for pod "React/Core":
  In Podfile:
    RNVoipPushNotification (from `../node_modules/react-native-voip-push-notification`) was resolved to 1.1.4, which depends on
      React/Core

None of your spec sources contain a spec satisfying the dependency: `React/Core`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

If anyone found this error then open node modules and navigate to react-native-voip-push-notification and open podspec file and change s.dependency 'React/Core' to s.dependency 'React-Core'.

But my request is to update this asap as i have waste my 8 hrs on this.

**Comment by zxcpoiu** [comment]
so you have solved by editing pod spec `s.dependency` from `React/Core` to `React-Core`?

**Comment by alipetarian** [comment]
@zxcpoiu I have solved as mentioned by @vinod20191992 .

Thanks @vinod20191992 .

**Comment by zxcpoiu** [comment]
@vinod20191992 @alipetarian 

Thank you

**Comment by redexp** [comment]
now we cannot install pod on react-native < 0.60

**Comment by ksitko** [comment]
Can confirm now in react-native 0.59 pod update and pod install provide this error:
`[!] Unable to find a specification for `React-Core` depended upon by `RNVoipPushNotification`
`

**Comment by alipetarian** [comment]
@ksitko https://prnt.sc/phrw9j

**Comment by zxcpoiu** [comment]
Yeah, I think it's a breaking changes in RN 0.60.

see: https://github.com/facebook/react-native/issues/25553#issuecomment-511065097
> Has we mentioned in the [blogpost](https://facebook.github.io/react-native/blog/2019/07/03/version-60), the Pods dependency has changed -> [2321b3f](https://github.com/facebook/react-native/commit/2321b3f)
> You need to change your Pod configuration to match the new format.

For RN < 0.60, the reversed workaround script can refer to
see: https://github.com/facebook/react-native/issues/25553#issuecomment-516660355

> Here is a little workaround I'm using right now, run this bash command in the root directory of the project which replaces React/Core with React-Core in all the npm modules
```grep -rl "s.dependency 'React/Core'" node_modules/ | xargs sed -i '' 's=React/Core=React-Core=g'```


### Change back from 'React-Core' to 'React/Core' ( for RN 0.59 users want to use current master branch )
`grep -rl "s.dependency 'React-Core'" node_modules/ | xargs sed -i '' 's=React-Core=React/Core=g'`
