### ISSUE TITLE
doesn't play custom sound

### ISSUE THREAD

**Issue by MuhammadAdnanRiaz** [react-native-webrtc/react-native-voip-push-notification#43]
i tried .aiff, .mp3 format  and placed my audio in resource/ 
and  setting the audio name to soundName  presentLocalNotification({soundName: 'azan_1.mp3'}),
but it still playing the default sound
can anyone give clear instruction how to set custom sound when notification arrive as there is no detail provide in package instruction

**Comment by MuhammadAdnanRiaz** [comment]
i fixed is by putting my sound file in root of xcode project 
![Screenshot 2019-10-22 at 12 15 58 PM](https://user-images.githubusercontent.com/26873607/67265097-4e8bd680-f4c6-11e9-86d6-faf28bcb554c.png)

**Comment by mofolo** [comment]
Just to add to this, custom sounds only work for Local Notifications, not VOIP Pushes. 
Callkit will always play the ringtone set in the users settings under: Settings > Sounds > Ringtones
