### ISSUE TITLE
Killing app because it never posted an incoming call to the system after receiving a PushKit VoIP push callback.

### ISSUE THREAD

**Issue by ThomasLarge** [react-native-webrtc/react-native-voip-push-notification#44]
Looks like Apple have changed some of there configuration on iOS13 and Xcode11, this is the full error 

Killing app because it never posted an incoming call to the system after receiving a PushKit VoIP push callback.

Are there any changes that need to be made to the package

**Comment by lonnylot** [comment]
@ThomasLarge I found https://github.com/react-native-webrtc/react-native-voip-push-notification/issues/36#issuecomment-510836436 which explains the issue and a solution.

**Comment by ThomasLarge** [comment]
@lonnylot Thanks for this! I have rewritten my whole app now but I'm going to try and test this too!

**Comment by lonnylot** [comment]
@ThomasLarge no problem. Out of curiosity how did you rewrite your app to handle the voip notifications?

**Comment by ThomasLarge** [comment]
@lonnylot so we changed the user experience to send push notifications every couple of seconds and then add `mutable-content: 1` to it and added some Swift code to change the way the push notifications show. We moved away from the CallKit stuff as I know Apple are going to be refreshing this next year. Based on what changes we might go back to the VoiP
