### ISSUE TITLE
didReceiveIncomingPushWithPayload not called in debug mode

### ISSUE THREAD

**Issue by rcidt** [react-native-webrtc/react-native-voip-push-notification#45]
I am using OneSignal to send push notifications. 

When I build my app for release mode, notifications arrive just fine. But when building for debug, the `didReceiveIncomingPushWithPayload` is never called and the notification is ignored. Although on OneSignal it says the notification was delivered.

**Comment by OriAmir** [comment]
@rcidt  did you find a solution ?  it's also not getting called in my app

**Comment by rcidt** [comment]
@OriAmir No I have not, but I managed to find a workaround to this, by [sending manual push notifications to APNS with cURL](https://medium.com/@kavithakumarasamy89/testing-your-ios-apns-certificate-a-developers-help-guide-d06c0f8d10d).

It seems like the issue lays somewhere on the OneSignal side.

**Comment by OriAmir** [comment]
@rcidt Tnx, but it's just for tests no? what do you do in prod? the 'didReceiveIncomingPushWithPayload  function not getting called for me also when I create release build .
Did you try Amazon service for voip ?

**Comment by rcidt** [comment]
@OriAmir seems we have fundamentally different issues.

VoIP Push Notifications work perfectly for me in Production builds. I don't use Amazon for voip.

I suggest you carefully read the new changes in iOS 13 regarding VoIP Notifications. [Here is a very straight forward article](https://onesignal.com/blog/ios-13-introduces-4-breaking-changes-to-notifications/#voip-changes).

Good luck

**Comment by ajnozari** [comment]
So voip push notifications work differently from debug (sandbox server) than on production mode. Keep in mind that just switching to the release scheme will not change this behavior as far as I can tell. Only pushing to TestFlight or the App Store will tell the app to get a production device token, which is what’s needed.  When you build in Xcode the app will request a sandbox device token, which is not valid for production URLs, only the sandbox one (this is when you trigger the notification via a web service or backend).

The best option would be to try pushing to TestFlight and see if the production url for voip push notification sending works then.

If you’re using a package on your backend that doesn’t allow setting the url make sure that it matches the following

Production: ssl://gateway.push.apple.com:2195
Dev: ssl://gateway.sandbox.push.apple.com:2195
