### ISSUE TITLE
didReceiveIncomingPushWithPayload it's triggered only in foreground

### ISSUE THREAD

**Issue by florindumitru** [react-native-webrtc/react-native-voip-push-notification#47]
didReceiveIncomingPushWithPayload() it's triggered only in foreground.

Here is my appdelegate

`/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <Firebase.h>
#import "RNCallKeep.h"
#import <PushKit/PushKit.h>                    /* <------ add this line */
#import "RNVoipPushNotificationManager.h"      /* <------ add this line */

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"ceva"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

// Handle updated push credentials
- (void)pushRegistry:(PKPushRegistry *)registry didUpdatePushCredentials:(PKPushCredentials *)credentials forType:(NSString *)type {
  // Register VoIP push token (a property of PKPushCredentials) with server
  [RNVoipPushNotificationManager didUpdatePushCredentials:credentials forType:(NSString *)type];
  
}

// Handle incoming pushes
- (void)pushRegistry:(PKPushRegistry *)registry didReceiveIncomingPushWithPayload:(PKPushPayload *)payload forType:(PKPushType)type withCompletionHandler:(void (^)(void))completion {
  // Process the received push
  [RNVoipPushNotificationManager didReceiveIncomingPushWithPayload:payload forType:(NSString *)type];
 
  NSString *uuid = [[[NSUUID UUID] UUIDString] lowercaseString];
  NSString *callerName = @"nume";
  NSString *handle = @"ext";
  NSLog(@"RNVoipPushNotificationManager ----- pushRegistry received");

  [RNCallKeep reportNewIncomingCall:uuid handle:handle handleType:@"generic" hasVideo:false localizedCallerName:callerName fromPushKit: YES];
  
  completion();
}

- (BOOL)application:(UIApplication *)application
continueUserActivity:(NSUserActivity *)userActivity
 restorationHandler:(void(^)(NSArray * __nullable restorableObjects))restorationHandler
{
  return [RNCallKeep application:application
            continueUserActivity:userActivity
              restorationHandler:restorationHandler];
}

@end
`

**Comment by batai278** [comment]
I have the same issue, also using RNCallKeep and Firebase (MLKit and Messaging for local pushes and Android waking up in background).

**Comment by batai278** [comment]
@florindumitru I made it work after adding lifecycle methods as in the following example:
https://github.com/hasyapanchasara/PushKit_SilentPushNotification/blob/master/Objective%20C%20Demo/PushKitDemoObjectiveC/PushKitDemoObjectiveC/AppDelegate.m

**Comment by tuanbm** [comment]
@batai278 it doesn't work.

**Comment by zxcpoiu** [comment]
Please read the new notes in the readme to see if there any missed part.

https://github.com/react-native-webrtc/react-native-voip-push-notification/blob/master/README.md#important-note

**Comment by zxcpoiu** [comment]
I'm closing this, if still encounter issue on 2.1.0 then open a new issue.
