### ISSUE TITLE
Event listeners aren't working

### ISSUE THREAD

**Issue by nikhildaga** [react-native-webrtc/react-native-voip-push-notification#5]
Nothing is logged when we do
```
    VoipPushNotification.addEventListener('localNotification', (notification) => {
     console.log(notification)
    })
      VoipPushNotification.presentLocalNotification({
          alertBody: "hello! "
      });
```

Also, register event is never triggered. 
```    
VoipPushNotification.addEventListener('register', (token) => {
      // send token to your apn provider server
 });
```
Please check

**Comment by eugenehp** [comment]
@nikhildaga did you figure this one out?

**Comment by nikhildaga** [comment]
@eugenehp : I think its a bug in library. Instead of listening for voip notification register event its listening for push notifications register event . 
When you turn on push notifications capability in xcode,  the register event will be triggered.
But, the token we get is for push notification, not voip.

**Comment by eugenehp** [comment]
interesting. thanks for sharing this @nikhildaga 
isn't voip push notification is a push notification in a nutshell?

how did you solve this issue after all?

**Comment by ianlin** [comment]
Sorry for late, quite busy recently.

We've been using this module for a year, everything works as expected. There is no chance this module listens to normal push notification events as long as you set up **PushKit** delegate correctly in your `AppDelegate.m`. Can you share your setup information as well as the versions of react-native and this module you use?

Cheers.

**Comment by nikhildaga** [comment]
Hi @ianlin, thanks for your reply.
I am using latest version of rn and this module.

I created a sample repo following exact steps in readme:  https://github.com/nikhildaga/voip

You can see the commits here: https://github.com/nikhildaga/voip/commits/master

The register event doesn't trigger.

I get the following warnings in xcode
![screen shot 2017-04-22 at 6 14 42 pm](https://cloud.githubusercontent.com/assets/655017/25309663/a32a05ea-2787-11e7-9135-cec45eb89d35.png)
![screen shot 2017-04-22 at 6 14 32 pm](https://cloud.githubusercontent.com/assets/655017/25309664/a32d74b4-2787-11e7-983d-c0337d0bbc78.png)

**Comment by ianlin** [comment]
Hi @nikhildaga, thanks for the repo!

I have tried your repo and yes the register is never called however I've found others had encountered the same problem ([this][1] and [this][2]) and those are resolved by **Enabling Push Notification Capability in Xcode**. :/

This is quite weird and since I've been enabling both in my own project so I haven't run into this problem. I will update this in the README and thanks for your reporting anyway!

Cheers,
Ian

[1]: http://stackoverflow.com/questions/34619187/pushkit-not-conceiving-credentials
[2]: http://stackoverflow.com/questions/41572699/ios-pushkit-registration-not-working-on-ios10

**Comment by Vetalyo** [comment]
@ianlin, hi!
I have the same problem - register event doesn't trigger.

In capabilities i have enabled "Push notification" and manually added VOIP support into info.plist
So I can't get VOIP token for testing.

**Comment by rcorrie** [comment]
@Vetalyo @nikhildaga I had the exact same problem. And as absurd as this sounds, restarting my phone fixed this for me. Hope it helps you too.

**Comment by grit96** [comment]
My `register` and `notification` events get triggered correctly, but the `localNotification` event is never triggered.

**Comment by divkhare** [comment]
I was trying to figure this out for a while. It turned out to be a simulator issue.
This might work, Run and build on a physical device through Xcode.

**Comment by CMLCNL** [comment]
same issue
