### ISSUE TITLE
app killed and screen locked

### ISSUE THREAD

**Issue by bmp123** [react-native-webrtc/react-native-voip-push-notification#50]
If app killed and screen locked [RNCallKeep][reportNewIncomingCall] doesn't open call screen.
Maybe You know how can I fix it?
ios: 13
in logs: 

> 17:35:25.630074+0500	appname	[RNVoipPushNotificationManager] constantsToExport currentState = background
17:35:28.160530+0500	appname	RNInCallManager.init(): initialized
	17:35:28.162852+0500	appname	RNInCallManager._checkRecordPermission(): recordPermission=granted
	17:35:28.166609+0500	appname	RNInCallManager._checkCameraPermission(): using iOS7 api. cameraPermission=undetermined
	17:35:28.289386+0500	appname	[RNCallKeep][setup] options = {
    appName = appname;
    maximumCallGroups = 1;
    supportsVideo = 0;
}
	17:35:28.290937+0500	appname	[RNCallKeep][getProviderConfiguration]
	7:35:29.664081+0500	onlinepbx	[react-native-permissions] ios.permission.MICROPHONE permission checked: granted
	17:35:29.664110+0500	appname	[RNVoipPushNotificationManager] voipRegistration
	17:35:29.666877+0500	appname	[RNCallKeep][reportNewIncomingCall] uuidString = 2452d430-bfca-4068-9cda-3d98f85ef878
	17:35:29.667721+0500	appname	[RNVoipPushNotificationManager] didReceiveIncomingPushWithPayload payload.dictionaryPayload = {
    aps =     {
        alert = "call";
    };
    "caller_id_name" = 04391076;
    handle = 04391076;
    type = call;
    uuid = "2452d430-bfca-4068-9cda-3d98f85ef878";
}, type = PKPushTypeVoIP
	17:35:29.667749+0500	appname	[RNVoipPushNotificationManager] handleRemoteNotificationReceived notification.userInfo = {
    aps =     {
        alert = "call";
    };
    "caller_id_name" = 04391076;
    handle = 04391076;
    type = call;
    uuid = "2452d430-bfca-4068-9cda-3d98f85ef878";
}

**Comment by zxcpoiu** [comment]
Is that logs from js side?

My only guess is:

You should make sure to report to callkit BEFORE execute `completion()` in `didReceiveIncomingPushWithPayload`

You can try directly use this first without bother js side to see whether callkit displayed or not, then adjust your flow.

```objc
- (void)pushRegistry:(PKPushRegistry *)registry didReceiveIncomingPushWithPayload:(PKPushPayload *)payload forType:(PKPushType)type withCompletionHandler:(void (^)(void))completion {
  
  [RNVoipPushNotificationManager didReceiveIncomingPushWithPayload:payload forType:(NSString *)type];

  // --- You should make sure to report to callkit BEFORE execute `completion()`
  [RNCallKeep reportNewIncomingCall:uuid handle:handle handleType:@"generic" hasVideo:false localizedCallerName:callerName fromPushKit: YES];
    
  completion();
}
```

**Comment by bmp123** [comment]
it's logs in native side. I was try display callkit first without js side, but callkit does not displayed. 
Only if screen locked 

> Is that logs from js side?
> 
> My only guess is:
> 
> You should make sure to report to callkit BEFORE execute `completion()` in `didReceiveIncomingPushWithPayload`
> 
> You can try directly use this first without bother js side to see whether callkit displayed or not, then adjust your flow.
> 
> ```objc
> - (void)pushRegistry:(PKPushRegistry *)registry didReceiveIncomingPushWithPayload:(PKPushPayload *)payload forType:(PKPushType)type withCompletionHandler:(void (^)(void))completion {
>   
>   [RNVoipPushNotificationManager didReceiveIncomingPushWithPayload:payload forType:(NSString *)type];
> 
>   // --- You should make sure to report to callkit BEFORE execute `completion()`
>   [RNCallKeep reportNewIncomingCall:uuid handle:handle handleType:@"generic" hasVideo:false localizedCallerName:callerName fromPushKit: YES];
>     
>   completion();
> }
> ```

**Comment by bmp123** [comment]
- (void)pushRegistry:(PKPushRegistry *)registry didReceiveIncomingPushWithPayload:(PKPushPayload *)payload forType:(PKPushType)type withCompletionHandler:(void (^)(void))completion {
    NSLog(@"PUSH PARAMS PAYLOAD:%@",payload);
    NSString *uuid = payload.dictionaryPayload[@"uuid"]; 
    NSString *handle = payload.dictionaryPayload[@"handle"];
    [RNCallKeep reportNewIncomingCall: uuid handle:handle handleType:@"email" hasVideo:false localizedCallerName:handle fromPushKit: YES];
    completion();
}
this is my code now. Callkeep does not display in locked screen

**Comment by zxcpoiu** [comment]
Sorry, I have no clues.

You can try simplify all factors like below, and check does log output from 1 to 4.

```objc
- (void)pushRegistry:(PKPushRegistry *)registry didReceiveIncomingPushWithPayload:(PKPushPayload *)payload forType:(PKPushType)type withCompletionHandler:(void (^)(void))completion {

  NSLog(@"111");
  [RNVoipPushNotificationManager didReceiveIncomingPushWithPayload:payload forType:(NSString *)type];

  NSLog(@"222");

  NSString *uuid = @"a7917b8e-1b78-45e6-9c99-a6321b2291ae";
  NSString *callerName = @"testCallerName";
  NSString *handle = @"testHandle";

  NSLog(@"333");
  [RNCallKeep reportNewIncomingCall:uuid handle:handle handleType:@"generic" hasVideo:false localizedCallerName:callerName fromPushKit: YES];

  NSLog(@"444");
  completion();
}
```

I'm also curious, my testing iOS 13 device does not have this issue.
Does this device is the only one that have this issue? Have you try on another device?

If I recall it correctly, some country like China does not allow to use CallKit for display incoming calls on lock screen. But I don't know if apple detect some thing on the device then disable CallKit conditionally. ( There are some rumors around it )

You can try on another device.

**Comment by bmp123** [comment]
Yes, I see this problem on iphone 6s and iphone 7 with same os version 13. when screen locked - in logs I see that my app init but didn't see console about voip push received

**Comment by bmp123** [comment]
And after this failed call if I tap to icon of my app - this open like a killed app. Not initialized

**Comment by bmp123** [comment]
and one more thing - these push notifications will be received when I open app.

**Comment by bmp123** [comment]
I solved this issue by adding react-native-background-timer when my app init

**Comment by zxcpoiu** [comment]
Congrates! But sounds strange. :confused:

**Comment by hungtd97** [comment]
> I solved this issue by adding react-native-background-timer when my app init

I faced this issue in IOS. What did you do by adding react-native-background-timer when your app woke?
