### ISSUE TITLE
handleRemoteNotificationRegistered issue

### ISSUE THREAD

**Issue by giftset** [react-native-webrtc/react-native-voip-push-notification#51]
![IMG_ED47905D92FF-1](https://user-images.githubusercontent.com/36372238/77250601-71e0ca80-6c8c-11ea-9c43-8d475e683885.jpeg)

I keep facing this module issue on ios debug mode.

How can i deal with this?

**Comment by zxcpoiu** [comment]
Seems you have invalid installation, try to remove every thing include node_module and pod, then try again
