### ISSUE TITLE
Can't show callkeep then app killed ios 13.4

### ISSUE THREAD

**Issue by romreed** [react-native-webrtc/react-native-voip-push-notification#53]
Someone can show how to call CallKeep in ios 13.4 then the application was killed?
   "react-native": "0.61.5",
    "react-native-callkeep": "3.0.10",
    "react-native-voip-push-notification": "^2.0.0",
`- (void)pushRegistry:(PKPushRegistry *)registry didReceiveIncomingPushWithPayload:(PKPushPayload *)payload forType:(PKPushType)type withCompletionHandler:(void (^)(void))completion {
  // --- Process the received push
  [RNVoipPushNotificationManager didReceiveIncomingPushWithPayload:payload forType:(NSString *)type];
  // --- NOTE: apple forced us to invoke callkit ASAP when we receive voip push
  // --- see: react-native-callkeep
  // --- Retrieve information from your voip push payload
   NSString *uuid = payload.dictionaryPayload[@"uuid"];
   NSString *callerName = [NSString stringWithFormat:@"%@ (Connecting...)", payload.dictionaryPayload[@"callerName"]];
   NSString *handle = payload.dictionaryPayload[@"handle"];
NSDictionary *extra = [payload.dictionaryPayload valueForKeyPath:@"call.boxt.one"];
   // --- You should make sure to report to callkit BEFORE execute `completion()`
        [RNCallKeep reportNewIncomingCall:uuid handle:handle handleType:@"generic" hasVideo:false localizedCallerName:callerName fromPushKit: YES];
  completion();
}
`

**Comment by ThanhNghia944** [comment]
@romreed  pls help me , how to test recieve  voip

**Comment by romreed** [comment]
@ThanhNghia944 Hi. I use Pusher.app to send Voip push notification and this code for getting a notification in my application.

```VoipPushNotification.requestPermissions(); // --- optional, you can use another library to request permissions
            VoipPushNotification.registerVoipToken(); // --- required

            VoipPushNotification.addEventListener('register', (token) => {
                // --- send token to your apn provider server
                console.log('register token', token);
                this.setState({tokenVoip: token});
            });

            VoipPushNotification.addEventListener('localNotification', (notification) => {
             
                console.log('localNotification');
       

            VoipPushNotification.addEventListener('notification', (notification) => {
             
                console.log('notification', notification);
         
            });


Then I send a notification in my debugger I see the console .

**Comment by ThanhNghia944** [comment]
@romreed thank you , i wil try ^^

**Comment by ThanhNghia944** [comment]
hi @romreed  can you help me 
I use apn to push voip with the following content
 

> note.badge = 1;
>    note.alert = "You have 111 new call";
>    note.payload = {
>       uuid: "0731961b-415b-44f3-a960-dd94ef3372fc",
>       callerName: "John Appleseed hi",
>       handle: "testemail@email.com",
>       extraPayLoad: "John Appleseed ID",
>       };
>    note.topic = "com.demo.practice.webrtc.voip";
>    apnProvider.send (note, [deviceToken])

--> in AppDelegate.m I have configured to receive data

> NSString *uuid = [payload.dictionaryPayload valueForKey:@"uuid"];
> NSString *callerName = [NSString stringWithFormat:@"%@ (Connecting...)", payload.dictionaryPayload[@"callerName"]];
> NSString *handle = [payload.dictionaryPayload valueForKey:@"handle"];
> NSDictionary *extra = [payload.dictionaryPayload valueForKey:@"extraPayLoad"];
> // --- You should make sure to report to callkit BEFORE execute completion()
> [RNCallKeep reportNewIncomingCall:uuid handle:handle handleType:@"email" hasVideo:false localizedCallerName:callerName fromPushKit: YES payload:extra];

-> When I get the message, I get the uuid, but I always get the error: parameter 'localizedName' cannot be nil '

> Demo WebRTC[3182:891552] [RNVoipPushNotificationManager] didReceiveIncomingPushWithPayload payload.dictionaryPayload = {
> aps = {
> alert = "You have 111 new call";
> badge = 1;
> };
> callerName = "John Appleseed hi";
> extraPayLoad = "John Appleseed ID";
> handle = "testemail@email.com";
> messageFrom = "John Appleseed";
> uuid = "0731961b-415b-44f3-a960-dd94ef3372fc";
> }, type = PKPushTypeVoIP
> 2020-04-21 23:59:58.059200+0700 Demo WebRTC[3182:891552] [RNVoipPushNotificationManager] handleRemoteNotificationReceived notification.userInfo = {
> aps = {
> alert = "You have 111 new call";
> badge = 1;
> };
> callerName = "John Appleseed hi";
> extraPayLoad = "John Appleseed ID";
> handle = "testemail@email.com";
> messageFrom = "John Appleseed";
> uuid = "0731961b-415b-44f3-a960-dd94ef3372fc";
> }
> 2020-04-21 23:59:58.059852+0700 Demo WebRTC[3182:891552] [RNCallKeep][reportNewIncomingCall] uuidString = 0731961b-415b-44f3-a960-dd94ef3372fc
> 2020-04-21 23:59:58.060032+0700 Demo WebRTC[3182:891552] [RNCallKeep][getProviderConfiguration]
> 2020-04-21 23:59:58.060395+0700 Demo WebRTC[3182:891552] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[CXProviderConfiguration initWithLocalizedName:]: parameter 'localizedName' cannot be nil'

**Comment by zxcpoiu** [comment]
Closing this, please report callkit related issue [here](https://github.com/react-native-webrtc/react-native-callkeep/issues)
