### ISSUE TITLE
Can't register completion handler in 2.1.0

### ISSUE THREAD

**Issue by CaptainJeff** [react-native-webrtc/react-native-voip-push-notification#56]
When I try to register the completion handler I continue to get the following error

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[RNVoipPushNotificationManager addCompletionHandler:completionHandler:]: unrecognized selector sent to class 0x102e4fcb8'

If i clikc on the function 

`[RNVoipPushNotificationManager addCompletionHandler:uuid completionHandler:completion];
`
I can see it exists.. I'm not sure what is happening. Any ideas?

**Comment by zxcpoiu** [comment]
Have you pass `uuid` into `addCompletionHandler` as well ?

**Comment by CaptainJeff** [comment]
Sorry for not responding @zxcpoiu 

I got this working a few months back by passing the completion handler in objective-c to `reportNewIncomingCall` 

thanks for helping!
