### ISSUE TITLE
Local Notification event listener is not logging any response

### ISSUE THREAD

**Issue by nikesh8** [react-native-webrtc/react-native-voip-push-notification#60]
I'm working with iOS for VoIP notification and I've used react-native-voip-push-notification to handle my VoIP notification.

I'm able to trigger localNotification using the following code:

```
VoipPushNotification.addEventListener('notification', (notification) => {
        console.log('Notification:::', notification)
        VoipPushNotification.presentLocalNotification({
          alertBody: notification.getMessage()
        });
      });
```
but local Notification listener is not logging out any notifications:

```
VoipPushNotification.addEventListener('localNotification', (notification) => {
      // --- when user click local push
     console.log('Local Notification:::', notification)
    });
```
I've enabled push notification, Background mode (VoIP notification, Background fetch, and Remote notification) from xCode capabilities. I'm using RN0.59.10. Is there something I'm missing?

Thanks in advance
#30

**Comment by zxcpoiu** [comment]
localNotification in this lib is broken and will be deprecated.
Use PushNotificationIOS to handle present notification instead
