### ISSUE TITLE
ts support

### ISSUE THREAD

**Issue by kinfkong** [react-native-webrtc/react-native-voip-push-notification#62]
seems not yet support typescript?
Thanks

**Comment by zxcpoiu** [comment]
I personally couldn't verify the TS support is working or not.
PR and test is welcome :)

**Comment by dayze** [comment]
Hello, see https://github.com/react-native-webrtc/react-native-voip-push-notification/pull/82 for typescript support ;)

**Comment by zxcpoiu** [comment]
merged, thanks @dayze
