### ISSUE TITLE
How to send voip push notification?

### ISSUE THREAD

**Issue by samad324** [react-native-webrtc/react-native-voip-push-notification#66]
Hi there,

i'm trying to intregrate voip push notification with callkeep. and i'm sending data like this:

```json
{
    "aps": {
        "alert": "Hello Push",
        "sound": "default"
    },
    "uuid": "12212",
    "callerName": "Samad",
    "handle": "Task",
    "extra": {}
}
```
but when my app recieve a push notification i got an exception in main.m file 
```Thread 1: Exception: "-[CXProvider reportNewIncomingCallWithUUID:update:completion:]: parameter 'UUID' cannot be nil"```

In AppDelegate.m
![image](https://user-images.githubusercontent.com/37283797/97421700-a1486b80-192e-11eb-9cec-cd47ca929172.png)

this is what i got from notification listner:
![image](https://user-images.githubusercontent.com/37283797/97421326-31d27c00-192e-11eb-9de7-5bbbd94861b3.png)

can anyone tell me what i'm doing wrong?

  "react-native": "0.63.1",
  "react-native-callkeep": "^3.1.1",
  "react-native-voip-push-notification": "^2.1.0",

**Comment by samad324** [comment]
Solved! this is issue with my uuid. changing the uuid was solved my issue.
```json
{
    "aps": {
        "alert": "Hello Push",
        "sound": "default"
    },
    "uuid": "0731961b-415b-44f3-a960-dd94ef3372fc",
    "callerName": "Samad",
    "handle": "Task",
    "extra": {}
}
```

**Comment by jason-shen** [comment]
> Solved! the issue is with my uuid. changing the uuid was solved my issue.
> 
> ```json
> 
> {
> 
>     "aps": {
> 
>         "alert": "Hello Push",
> 
>         "sound": "default"
> 
>     },
> 
>     "uuid": "0731961b-415b-44f3-a960-dd94ef3372fc",
> 
>     "callerName": "Samad",
> 
>     "handle": "Task",
> 
>     "extra": {}
> 
> }
> 
> ```

Is this object comes from a push callback? Can I ask which provider you using for push notification

**Comment by fukemy** [comment]
hi @samad324 , can u guide me how to make pushkit triggered? I dont know how to do it? Thanks so much
