### ISSUE TITLE
help need it for ios13

### ISSUE THREAD

**Issue by jason-shen** [react-native-webrtc/react-native-voip-push-notification#67]
Hi All

firstly this is a awesome plugin, i have starting looking into this, have come to an problem i don't understand, if any one could help me out that would be great.

here is the problem, i looked through the examples, and understand how android works, you just call the initial connection function of the voip service, and then open the app, but in ios, i couldn't find a good example of how the whole flow works, as ios you can't bring the app in foreground, so how do we execute the init script to connect to the socket server, and if the user client the open app button how would you handle that

i hope i have explain it clear 

any help would be awesome

thanks advance

Jason

**Comment by zxcpoiu** [comment]
This libs only support ios and handles ios PushKit Voip notification only.
I guess you are referring to CallKit?
If so, check https://github.com/react-native-webrtc/react-native-callkeep
