### ISSUE TITLE
unlock phone when swipe to answer an incoming call

### ISSUE THREAD

**Issue by vitorlsouza** [react-native-webrtc/react-native-voip-push-notification#68]
when receiving a call and the app is in background and phone locked when you swipe to answer it doesnt swipe to unlock and answer, just answer so you're presented the swipe to unlock normal apple screen when your phone wakes up.

when the phone wakes up, the app does not launch, because it already tried to launch when the incoming call was answered and the phone was blocked.

Is there a way to unlock the phone when I swipe to answer the call and the app only launches after the phone is unlocked?

**Comment by zxcpoiu** [comment]
Apple forced us to present CallKit each time when received voip push.
AFAIK, the behavior of CallKit is not controlled us, when the screen is locked, the CallKit swiper is just answer the call.
If user wants to go to the app UI, they should first press buttons on CallKit then type the screen lock password.

You might tweak CallKit UI, but it is out of scope of this lib. check CallKit is not controlled in this lib, check https://github.com/react-native-webrtc/react-native-callkeep instead
