### ISSUE TITLE
Not receiving FCM push notification after installing rn-voip-push-notification.

### ISSUE THREAD

**Issue by subinsuresh991** [react-native-webrtc/react-native-voip-push-notification#71]
This is happening only in iOS.

**Comment by zxcpoiu** [comment]
I guess it is because `requestPermission` messed around.

Just do not invoke `requestPermission` on 2.x version.
Or try 3.0.0, which removed `requestPermission` thoroughly and makes this lib completely nothing to do with normal APN push.
