### ISSUE TITLE
What library to use for Android voip notifications and background calling?

### ISSUE THREAD

**Issue by stephanoparaskeva** [react-native-webrtc/react-native-voip-push-notification#73]
I can set this up for IOS but I cannot find out how to allow background calling for android. Do you mind pointing me in the right direction?

Cheers 🍻

**Comment by zxcpoiu** [comment]
Android does not have the concept of `voip` push, it's just use the regular push FCM (Firebase Cloud Messaging), and pass `priority` to determine the priority.

There are bunch of info there on the internet, you might want to check https://github.com/react-native-webrtc/react-native-callkeep first and may be https://github.com/zo0r/react-native-push-notification or https://github.com/invertase/react-native-firebase/tree/master/packages/messaging
