### ISSUE TITLE
Unused imports

### ISSUE THREAD

**Issue by Romick2005** [react-native-webrtc/react-native-voip-push-notification#74]
Hi @zxcpoiu, great job on the voip push notifications!
I have a small question. While I was inspecting your code I noticed that there are unused imports:
#import <React/RCTConvert.h>
#import <React/RCTUtils>
I am new to Objective-C so I cannot be 100% sure about this. So if they are really unneeded, should I fire a PR for that or you will just adjust that in next release?

**Comment by zxcpoiu** [comment]
I was refer to some boilerplate somewhere, if you removed the two import and everything are build and work as usual, it's welcome to fire a PR then :+1:
