### ISSUE TITLE
[IOS 14.0] Cannot receive voip push notification in mode background/kill app version 3.0.0

### ISSUE THREAD

**Issue by meosieudang** [react-native-webrtc/react-native-voip-push-notification#75]
![Screen Shot 2020-12-15 at 17 42 48](https://user-images.githubusercontent.com/45912335/102204961-1b43ac80-3efd-11eb-9af4-ef8ec999c23c.png)

The image file above is log when in app. But when I'm in mode background/kill app not working receive voip push notification, just working when i in app. Please help me :( @zxcpoiu 

Here is my config: 
![Screen Shot 2020-12-15 at 17 56 50](https://user-images.githubusercontent.com/45912335/102206321-fb14ed00-3efe-11eb-8a79-fe13e01ddd18.png)
![Screen Shot 2020-12-15 at 17 57 00](https://user-images.githubusercontent.com/45912335/102206332-023bfb00-3eff-11eb-996a-f65e2141358d.png)

"react-native-callkeep": 4.0.1
"react-native-voip-push-notification": "^3.0.0",

**Comment by meosieudang** [comment]
@zxcpoiu , i test on device ios 13.7 => working kill app/background. But my devices ios 14.0.1 => not working with state background/killed app :(

**Comment by onebot-collab** [comment]
facing same issue. please

**Comment by nhjuhoang** [comment]
me too

**Comment by mikeangelsilva** [comment]
me too. i'm on ios 14. anybody have a workaround on this? thank you.

**Comment by nhjuhoang** [comment]
After I found out it might be due to the apple block 24h ,I tried it again and receive notification when app background / killed

**Comment by nhjuhoang** [comment]
Answer from @mudassirzulfiqar on Github (Thanks to him). I got voip push notification after uninstall and re-install my app. Now, I will call reportNewIncomingCall in didReceiveIncomingPushWith

**Comment by zxcpoiu** [comment]
I don't have any issues on ios 14. Either on 3.0.0 or 3.1.0.

My suggestion (check list) would be:

* Register PushKit  delegate ASAP on the native side.
* Make sure you DID report to CallKit successfully (without error or crash) on EVERY voip notification, or it will be blocked by apple.

**Comment by zxcpoiu** [comment]
@meosieudang

Do you have subscribed `didLoadWithEvents` on JS?
The push event might occur earlier before the JS bridge initialized. So you need `didLoadWithEvents` to cache it.

Please check the README usage, and put `didLoadWithEvents` to the first subscribed listener.

**Comment by onebot-collab** [comment]
> 
> 
> I don't have any issues on ios 14. Either on 3.0.0 or 3.1.0.
> 
> My suggestion (check list) would be:
> 
>     * Register PushKit  delegate ASAP on the native side.
> 
>     * Make sure you DID report to CallKit successfully (without error or crash) on EVERY voip notification, or it will be blocked by apple.

nice sounds, and i worked fine in background and killed apps, thx. Next issues I found out can't handle answer incoming call. Im sure to have subscribed the README correctly. Please help

**Comment by zxcpoiu** [comment]
This lib only handles `register voip push token` and `propagate voip push`, if you are referring to CallKit, please check and report on https://github.com/react-native-webrtc/react-native-callkeep, there have lots of discussions and examples.
