### ISSUE TITLE
No known class method for selector 

### ISSUE THREAD

**Issue by tuannvitt** [react-native-webrtc/react-native-voip-push-notification#78]
![Screen Shot 2021-01-11 at 21 40 14](https://user-images.githubusercontent.com/38986433/104195740-97c2a000-5455-11eb-98e3-cd6aef9e5e81.png)

**Comment by zxcpoiu** [comment]
I suggest you to follow the CallKeep readme carefully and make sure you use the right api arguments, and the variables are all defined.

This is callkeep setup related issue and should report / ask on callkeep issue or stackoverflow.
I'm closing this now.

**Comment by Schavras** [comment]
For future reference, use this snipper from the Callkeep
https://github.com/react-native-webrtc/react-native-callkeep#pushkit
