### ISSUE TITLE
register event not working

### ISSUE THREAD

**Issue by CMLCNL** [react-native-webrtc/react-native-voip-push-notification#79]
I looked at all the solutions offered, I looked at the answers to those who shared this error before, but none of them worked. I have been working for 1 day and haven't even once received a token. I've tried it on a few phones. It doesn't work. Please help. 

```
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  [RNVoipPushNotificationManager voipRegistration];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"Myapp"
                                            initialProperties:nil];
```

```
 /* Add PushKit delegate method */

// --- Handle updated push credentials
- (void)pushRegistry:(PKPushRegistry *)registry didUpdatePushCredentials:(PKPushCredentials *)credentials forType:(PKPushType)type {
  // Register VoIP push token (a property of PKPushCredentials) with server
  [RNVoipPushNotificationManager didUpdatePushCredentials:credentials forType:(NSString *)type];
}

- (void)pushRegistry:(PKPushRegistry *)registry didInvalidatePushTokenForType:(PKPushType)type
{
  // --- The system calls this method when a previously provided push token is no longer valid for use. No action is necessary on your part to reregister the push type. Instead, use this method to notify your server not to send push notifications using the matching push token.
}
```

```

import VoipPushNotification from 'react-native-voip-push-notification';

 VoipPushNotification.addEventListener('register', (token) => {
                console.log(token, "voip token");
 });

```

**Comment by Romick2005** [comment]
Have you tried to subscribe to didLoadWithEvents event?

**Comment by CMLCNL** [comment]
> Have you tried to subscribe to didLoadWithEvents event?

No, i dont try this. Because i use this library 1 year..

**Comment by Romick2005** [comment]
Than you should try. Also you need to keep track of library updates more frequently than once o year bases.

**Comment by CMLCNL** [comment]
`94c19d0be742ce6ab01ea2545fb2a5518c1dcac3044f62ca666ae9cdb8b6eaba` is this a true voip token?

When i try like this its work.

```
 VoipPushNotification.registerVoipToken();

            VoipPushNotification.addEventListener('register', (deviceToken) => {
                console.log(deviceToken, "voip token");
            });
```

Before i removed this from appdelegate.m

`[RNVoipPushNotificationManager voipRegistration];`

**Comment by Romick2005** [comment]
Let me try to explain. When is in background there is no react native app running so that means that no javascript is running. There are two ways to init events for voip: 1) From objective c 2) From js add listener. But in js case if app in backround register event is fired before app js part attach "register" is initialized. That is why it does not for you. Bu the way you can check that by sending voip notification when app is running it should work for you. But when it is not running (in background mode) you should listen cached register event on didLoadWithEvents and there you will find register event that was fired by native code before app javascript started. Can you please verify/check this statement?

**Comment by CMLCNL** [comment]
I want to start the application with Voip and run a callkit after connecting to the chat on the js side.  Just this. How i can catch this event.

**Comment by CMLCNL** [comment]
I do everything but ios 13.x never take voip token. @Romick2005

**Comment by Romick2005** [comment]
Have you tried NSLog on the native side when receive notification. Try to debug

**Comment by swiety85** [comment]
I also have a problem with listeners. I see that in the native code everything looks good and the following line is executed:
https://github.com/react-native-webrtc/react-native-voip-push-notification/blob/ab54fd96badcf4eec56e1b93bb9f7fb353f57c7f/ios/RNVoipPushNotification/RNVoipPushNotificationManager.m#L94
but no listeners are called on the JS side.

**Comment by Romick2005** [comment]
Have you tried to subscribe to didLoadWithEvents event?

**Comment by zxcpoiu** [comment]
Thanks @Romick2005 for the help.

@CMLCNL please try 3.1.0, now it fires `register` enevt with the latest cached token for you if you have register voip token on the native side and call `registerVoipToken` on JS side again.

**Comment by CMLCNL** [comment]
Everything is work in iOS 14.x but i am not sure for ios 13.x

Thank you for your help! @Romick2005 and @zxcpoiu

**Comment by CMLCNL** [comment]
Works in ios 13.x.

**Comment by zxcpoiu** [comment]
Congrate! 

@swiety85
You can try to subscribe JS events listener ASAP as well and the first one is `didLoadWithEvents`, please check README usage.

I'm closing this now.

**Comment by shivi126** [comment]
@Romick2005  I am trying to generate voip token using VoipPushNotification.registerVoipToken()
It is successfully generating token on ios 17 but it is not working in ios 15.5 and lower

I have added listener for the didLoadWithEvents. However, it does not fire for ios 15.5. Here is the output from ios 15.5:

`[RNVoipPushNotificationManager] voipRegistration is already registered. return _lastVoipToken`

But there is not token returned.

**Comment by KolissnikBogdan** [comment]
+ 1
