### ISSUE TITLE
Sometimes Incoming Call UI does not display in background: Voip Push Dropped On Floor

### ISSUE THREAD

**Issue by stephanoparaskeva** [react-native-webrtc/react-native-voip-push-notification#84]
Most of the time the call UI appears in background. But sometimes it does not. This has been happening more and more to me and it occurs on either 1 phone or the other phone. 

I can verify that the VOIP push request is sent via my dashboard (sender string@email.com):

<img width="1313" alt="Screenshot 2021-03-24 at 21 45 36" src="https://user-images.githubusercontent.com/40718272/112388323-e2c92100-8cea-11eb-955d-5e939f981f73.png">

And I know this is to the correct APNS_VOIP token as this is the subscription of the recipient (fire@email.com)

<img width="655" alt="Screenshot 2021-03-24 at 21 47 46" src="https://user-images.githubusercontent.com/40718272/112388377-f5435a80-8cea-11eb-8b7f-7e2b291e6005.png">

Here is a log of the notification:
```js
 "log":[
      {
         "device_token":"2d96137af63ad49757a600aa199a02fa8d667947ebbf9a1d6f07705ed3cf6579",
         "delivered_at":"2021-03-24T21:44:51+00:00",
         "failed_at":null,
         "error_code":null,
         "error_description":null
      }
```

But I don't see any call UI and this breakpoint **does not run**:

<img width="877" alt="Screenshot 2021-03-24 at 21 51 44" src="https://user-images.githubusercontent.com/40718272/112388509-291e8000-8ceb-11eb-966a-4e3f2e37db92.png">

Below is my method:
```js
// --- Handle incoming pushes
- (void)pushRegistry:(PKPushRegistry *)registry didReceiveIncomingPushWithPayload:(PKPushPayload *)payload forType:(PKPushType)type withCompletionHandler:(void (^)(void))completion {
  
  
  // --- NOTE: apple forced us to invoke callkit ASAP when we receive voip push
  // --- see: react-native-callkeep
  
  // --- Retrieve information from your voip push payload
  NSString *uuid = payload.dictionaryPayload[@"uuid"];
  // @"%@ (Connecting...)"
  NSString *callerName = [NSString stringWithFormat:@"%@", payload.dictionaryPayload[@"callerName"]];
  NSString *handle = payload.dictionaryPayload[@"handle"];
  
  // This is for notifications that are sent specifically for receiver to end callkeep
  int isReject = [payload.dictionaryPayload[@"isReject"] isEqual:@"YES"] ? YES : NO;
  if (isReject) {
    completion();
    return [RNCallKeep endCallWithUUID: uuid reason:YES];
  }
  
  // --- this is optional, only required if you want to call `completion()` on the js side
  [RNVoipPushNotificationManager addCompletionHandler:uuid completionHandler:completion];
  
  // --- Process the received push
  [RNVoipPushNotificationManager didReceiveIncomingPushWithPayload:payload forType:(NSString *)type];
  
  int hasVideo = [payload.dictionaryPayload[@"hasVideo"] isEqual:@"YES"] ? YES : NO;
  
  
  // --- You should make sure to report to callkit BEFORE execute `completion()`
  // RNCallKeep >4.0.0
  [RNCallKeep reportNewIncomingCall: uuid
                             handle: handle
                         handleType: @"generic"
                           hasVideo: hasVideo
                localizedCallerName: callerName
                    supportsHolding: NO
                       supportsDTMF: NO
                   supportsGrouping: NO
                 supportsUngrouping: NO
                        fromPushKit: YES
                            payload: payload.dictionaryPayload
              withCompletionHandler: completion];
  completion();
}
```

This is JS for sending the message:

```js
  const event = {
    notificationType: NOTIFICATION_TYPE_PUSH as any,
    payload: {
      ios_voip: 1,
      uuid: session.id,
      callerName: name, // Send initiator name to other phone
      handle: name, // Send initiator name to other phone
      hasVideo: isVideo ? 'YES' : 'NO',
      // key: vlue
    },
    recipientsIds: payload.opponentsIds, // users' IDs to deliver notification
    senderId: currentUser?.id || 0, // ID of the user who created the event
    type: ONE_SHOT as any,
  };
  try {
    await QB.events.create(event);
  } catch (err) {
```

### Dropped on the floor
Images from the console while checking logs for app that has not opened and filtering for 'voip' show the error message:

**VoIP push for app <private> dropped on the floor**

Here are images:
<img width="1375" alt="Screenshot 2021-03-28 at 16 26 02" src="https://user-images.githubusercontent.com/40718272/112757764-105fe400-8fe3-11eb-9b09-db3e003727a0.png">

<img width="1155" alt="Screenshot 2021-03-28 at 16 32 45" src="https://user-images.githubusercontent.com/40718272/112757886-7d737980-8fe3-11eb-9642-5a52740ac557.png">

**Comment by nguyenxuankiet262** [comment]
+ 1

**Comment by Romick2005** [comment]
Do you have completion callback called?

Can you try to call completion afterwards and also pass it to the DisplayIncomingCall not nil, but completion. I have read that if you do not call completion callback within 30sec your app will stop handle any PN. In that case only remove and then install app help me, even in debug mode.
As Onesignal response was success, but ios did not pass voip notification to the app.
```
// --- Handle incoming pushes
-(void) pushRegistry: (PKPushRegistry *) registry didReceiveIncomingPushWithPayload: (PKPushPayload *) 
payload forType: (PKPushType) type 
withCompletionHandler: (void (^)(void)) completion { // completion !!!!

  // --- Retrieve information from your voip push payload
  NSDictionary *payloadDataCustom = payload.dictionaryPayload[@"custom"];
  NSMutableDictionary *payloadData = payloadDataCustom[@"a"];
  NSDictionary *caller = payloadData[@"caller"];
  NSNumber *reasonId = payloadData[@"reasonId"];
  NSString *callUUID = payloadData[@"callUUID"];
  NSString *handle = payloadData[@"handle"];

  // --- Process the received push
  [RNVoipPushNotificationManager didReceiveIncomingPushWithPayload: payload forType: (NSString *) type];

  // --- You should make sure to report to callkit BEFORE execute `completion()`
  [RNCallKeep reportNewIncomingCall: callUUID
                             handle: handle
                         handleType: @"generic"
                           hasVideo: payloadData[@"hasVideo"]
                localizedCallerName: caller[@"firstName"]
                    supportsHolding: NO
                       supportsDTMF: NO
                   supportsGrouping: NO
                 supportsUngrouping: NO
                        fromPushKit: YES
                            payload: payloadData
              withCompletionHandler: completion // !!!!
   ];

  // --- You don't need to call it if you stored `completion()` and will call it on the js side.
  completion(); // !!!!
}
```

**Comment by stephanoparaskeva** [comment]
> Do you have completion callback called?
> 
> 
> 
> Can you try to call completion afterwards and also pass it to the DisplayIncomingCall not nil, but completion. I have read that if you do not call completion callback within 30sec your app will stop handle any PN. In that case only remove and then install app help me, even in debug mode.
> 
> As Onesignal response was success, but ios did not pass voip notification to the app.
> 
> ```
> 
> // --- Handle incoming pushes
> 
> -(void) pushRegistry: (PKPushRegistry *) registry didReceiveIncomingPushWithPayload: (PKPushPayload *) 
> 
> payload forType: (PKPushType) type 
> 
> withCompletionHandler: (void (^)(void)) completion { // completion !!!!
> 
> 
> 
>   // --- Retrieve information from your voip push payload
> 
>   NSDictionary *payloadDataCustom = payload.dictionaryPayload[@"custom"];
> 
>   NSMutableDictionary *payloadData = payloadDataCustom[@"a"];
> 
>   NSDictionary *caller = payloadData[@"caller"];
> 
>   NSNumber *reasonId = payloadData[@"reasonId"];
> 
>   NSString *callUUID = payloadData[@"callUUID"];
> 
>   NSString *handle = payloadData[@"handle"];
> 
> 
> 
>   // --- Process the received push
> 
>   [RNVoipPushNotificationManager didReceiveIncomingPushWithPayload: payload forType: (NSString *) type];
> 
> 
> 
>   // --- You should make sure to report to callkit BEFORE execute `completion()`
> 
>   [RNCallKeep reportNewIncomingCall: callUUID
> 
>                              handle: handle
> 
>                          handleType: @"generic"
> 
>                            hasVideo: payloadData[@"hasVideo"]
> 
>                 localizedCallerName: caller[@"firstName"]
> 
>                     supportsHolding: NO
> 
>                        supportsDTMF: NO
> 
>                    supportsGrouping: NO
> 
>                  supportsUngrouping: NO
> 
>                         fromPushKit: YES
> 
>                             payload: payloadData
> 
>               withCompletionHandler: completion // !!!!
> 
>    ];
> 
> 
> 
>   // --- You don't need to call it if you stored `completion()` and will call it on the js side.
> 
>   completion(); // !!!!
> 
> }
> 
> ```

Yes I have the completion exactly how you have it, and still experience the problem

**Comment by Romick2005** [comment]
You should try to find out reproducible steps for this to fix it. It is not random bug.

**Comment by stephanoparaskeva** [comment]
> You should try to find out reproducible steps for this to fix it. It is not random bug.

More logs were provided at the end of the issue

**Comment by gwenoleR** [comment]
You should try to reinstall your app.

If the system failed to report the call few times the voip notifications are not display

**Comment by Romick2005** [comment]
@stephanoparaskeva @nguyenxuankiet262

Do you still have this issue? Are you sure it is caused by this module?

**Comment by stephanoparaskeva** [comment]
> @stephanoparaskeva @nguyenxuankiet262
> 
> Do you still have this issue? Are you sure it is caused by this module?

I received this issue when I had logic that prevented `reportNewIncomingCall`

```js
  int isReject = [payload.dictionaryPayload[@"isReject"] isEqual:@"YES"] ? YES : NO;
  if (isReject) {
    completion();
    return [RNCallKeep endCallWithUUID: uuid reason:YES];
  }
  ```

Since removing this, the issue has not occurred again. 

How about yourself, did you experience this issue?

**Comment by Romick2005** [comment]
I also do not have this issue.

**Comment by stephanoparaskeva** [comment]
> I also do not have this issue.

Can you share your code?

What do you think are you doing differently ?

**Comment by Romick2005** [comment]
I have this:
![image](https://user-images.githubusercontent.com/17779660/118798732-a65b1100-b8a6-11eb-9e6e-35d47353a9a9.png)
and do not have this issue.

**Comment by Romick2005** [comment]
But anyway I believe that this issue is not related to this library, so I suggest to close this one.

**Comment by stephanoparaskeva** [comment]
Yes I agree, cheers 👍
