### ISSUE TITLE
example

### ISSUE THREAD

**Issue by johnwnowlin** [react-native-webrtc/react-native-voip-push-notification#9]
I am new to the IOS react land. I have react-native-push-notifications work but am trying to add voip. Is there a simple example available somewhere? My main question right now is what `Add PushKit delegate method` means in the appDelegate.m.

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{

...

/* Add PushKit delegate method */
```

**Comment by ianlin** [comment]
Hi, I would recommend you to read [this][1].

Basically to add PushKit delegate in your `AppDelegate.m` is something similar to [adding normal push notification delegates][2].

Hope it helps!

[1]: https://developer.apple.com/library/content/documentation/Performance/Conceptual/EnergyGuide-iOS/OptimizeVoIP.html
[2]: https://facebook.github.io/react-native/docs/pushnotificationios.html

**Comment by johnwnowlin** [comment]
Thank you, I am receiving VOIP notifications now, except for the initial notification that occurs when the app is awoken from forced closed. I can see that the app is receiving the notification 
` <Notice>: [RNVoipPushNotificationManager] didReceiveIncomingPushWithPayload payload.dictionaryPayload = {` , but the VoipPushNotification "notification" event is not triggered.  I see a comment about 'popInitialNotification', is there something I have to set to receive the initial notification?

**Comment by platonish** [comment]
@johnwnowlin Were you able to solve for this? I'm faced with the exact same problem. There are multiple other issues stating the same problem, like #16, #14 or [#15(comment)](https://github.com/ianlin/react-native-voip-push-notification/issues/15#issuecomment-346811385).
