### ISSUE TITLE
unrecognized selector sent to instance

### ISSUE THREAD

**Issue by whoiswentz** [react-native-webrtc/react-native-voip-push-notification#98]
I'm getting this error 

Thread 1: "-[EXExpoAppDelegate pushRegistry:didUpdatePushCredentials:forType:]: unrecognized selector sent to instance 0x283125060"

I setup the library exactly readme shows

**Comment by Jonatthu** [comment]
Funny I'm getting the same error when using Expo singleton to not modify the AppDelegate but I don't get the error whenever I modify the AppDelegate file

**Comment by xubmuajkub** [comment]
@whoiswentz Have you solve this yet?

**Comment by shawarmaz** [comment]
Getting this too, why is this closed in the first place? 

Reopen please
